 - name: Update cache
   apt:
     update_cache: yes

 - name: Install packages
   apt:
     name: "{{ packages }}"
     update_cache: yes
   vars:
     packages:
     - mc
     - bc
     - bind9
     - nscd
     - git
     - make
     - gcc
     - python3
   tags:
   - packages

 - sysctl:
     name: vm.max_map_count
     value: 95120
     sysctl_set: yes
   tags:
     - sysctl

 - sysctl:
     name: kernel.pid_max
     value: 95120
     sysctl_set: yes
   tags:
     - sysctl

 - sysctl:
     name: kernel.threads-max
     value: 240260
     sysctl_set: yes

 - sysctl:
     name: net.ipv4.tcp_tw_reuse
     value: 1
     sysctl_set: yes
   tags:
     - sysctl

 - sysctl:
     name: net.ipv4.tcp_fin_timeout
     value: 15
     sysctl_set: yes
   tags:
     - sysctl

 - name: Get git repo 3proxy
   git:
     repo: https://github.com/z3APA3A/3proxy.git
     dest: /root/3proxy

 - name: Make 3proxy
   shell: cd /root/3proxy && make -f Makefile.Linux
   args:
     executable: /bin/bash
   ignore_errors: true

 - name: Copy 3proxy binary
   shell: cp -f /root/3proxy/bin/3proxy /root/3proxy/3proxy

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'listen-on-v6'
     replace: 'listen-on'
   tags:
   - dns

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'any'
     replace: '127.0.0.1'
   tags:
   - dns

 - name: Change nameservers
   replace:
     path: /etc/network/interfaces
     regexp: '8.8.8.8'
     replace: '127.0.0.1'
   tags:
     - dns

 - name: Copy resolv.conf
   copy:
     src: resolv.conf
     dest: /etc/resolv.conf
     mode: 0744
   tags:
   - dns

 - name: Restart bind9 service
   service:
     name: bind9
     state: restarted
   tags:
   - dns

 - name: Copy script
   copy:
     src: scripts/setup_ipv4.py
     dest: /root/setup_ipv4.py
     mode: 0744

 - name: Create 3proxy config
   shell: /root/setup_ipv4.py '{{ proxy_login }}' '{{ proxy_password }}' '{{ subnet }}' '{{ ansible_host }}' '{{ start_port }}' '{{ input }}'

 - name: Send systemd .service file
   copy:
     src: 3proxy.service
     dest: /etc/systemd/system/3proxy.service
     mode: 0744
   tags: systemd

 - name: start 3proxy.service
   systemd: state=restarted name=3proxy daemon_reload=yes enabled=yes
   tags: systemd
